"""empty message

Revision ID: 1dff62952f4d
Revises: bdb224bc51ab
Create Date: 2020-09-28 22:32:19.629025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dff62952f4d'
down_revision = 'bdb224bc51ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roadtrips_user_id_fkey', 'roadtrips', type_='foreignkey')
    op.drop_column('roadtrips', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('roadtrips', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # op.create_foreign_key('roadtrips_user_id_fkey', 'roadtrips', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
